Makefile: remove dataplane operator reference
The dataplane operator is replaced by the openstack operator and the
edpm targets were cloning the openstack operator as a dataplane
directory:
```
Cloning repo: git clone  -b main https://github.com/openstack-k8s-operators/openstack-operator.git dataplane-operator
```

Which would cause this error later:
```
error: must build at directory: not a valid directory: evalsymlink failure on '/home/stack/install_yamls/out/operator/openstack-operator/config/samples/dataplane/preprovisioned' : lstat /home/stack/install_yamls/out/operator/openstack-operator: no such file or directory
make: *** [Makefile:795: edpm_deploy_prep] Error 1
```

This patch will replace `dataplane` to `openstack` in the edpm targets.

Signed-off-by: Brendan Shephard <bshephar@redhat.com>